#!/bin/sh
#
# This build is run inside of a manylinux2014_x86_64 container based
# on Fedora Linux.
#
set -e
yum install -y autoconf automake gcc git libtool libyaml-devel make rpm-build
cd /libvna
./bootstrap
./configure
make -j12 rpm
