name: Test Manylinux

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: quay.io/pypa/manylinux2014_x86_64:latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Run the Test Build
      run: |
        yum install -y autoconf automake gcc git libtool libyaml-devel \
            make rpm-build
        ./bootstrap
        ./configure
        make -j12 check
        make distcheck
